EcomTest/Models/ErrorViewModel.cs
using System;

namespace EcomTest.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EcomTest/Controllers/DisbursementController.cs
using EcomTest_Business.BusinessLogics.Interfaces;
using EcomTest_Business.DTO.Request;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace EcomTest.Controllers
{
    public class DisbursementController : Controller
    {
        private readonly IDisbursement _business;
        public DisbursementController(IDisbursement disbursement)
        {
            _business = disbursement;
        }
        public IActionResult EquatedMonthlyInstallment()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EquatedMonthlyInstallment(DisbursementRequest disbursement)
        {
            if (!ModelState.IsValid) return View();

            await _business.SaveDistursement(disbursement);

            return View(disbursement);
        }
    }
}

EcomTest/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using EcomTest.Models;

namespace EcomTest.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EcomTest/ViewComponents/ScheduleViewComponent.cs
using EcomTest_Business.BusinessLogics.Interfaces;
using EcomTest_Business.DTO.Request;
using EcomTest_Business.DTO.Response;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace EcomTest.ViewComponents
{
    [ViewComponent(Name = "Schedule")]
    public class ScheduleViewComponent : ViewComponent
    {
        private readonly ISchedule _schedule;

        public ScheduleViewComponent(ISchedule schedule)
        {
            _schedule = schedule;
        }

        public async Task<IList<ScheduleResponse>> GenerateSchechule(DisbursementRequest disbursement)
        {
            return await Task.FromResult(await _schedule.GenerateSchechule(disbursement));
        }

        public async Task<IViewComponentResult> InvokeAsync(DisbursementRequest disbursement)
        {
            return View(await GenerateSchechule(disbursement));
        }
    }
}

EcomTest/Views/Disbursement/EquatedMonthlyInstallment.cshtml
@model EcomTest_Business.DTO.Request.DisbursementRequest

@{
    ViewData["Title"] = "EquatedMonthlyInstallment";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="EquatedMonthlyInstallment">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Cust_Name" class="control-label"></label>
                <input asp-for="Cust_Name" class="form-control" />
                <span asp-validation-for="Cust_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Disb_Date" class="control-label"></label>
                <input asp-for="Disb_Date" class="form-control" />
                <span asp-validation-for="Disb_Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Disb_Amount" class="control-label"></label>
                <input asp-for="Disb_Amount" class="form-control" />
                <span asp-validation-for="Disb_Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Int_Rate" class="control-label"></label>
                <input asp-for="Int_Rate" class="form-control" />
                <span asp-validation-for="Int_Rate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Months" class="control-label"></label>
                <input asp-for="Months" class="form-control" />
                <span asp-validation-for="Months" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EMS_St_Date" class="control-label"></label>
                <input asp-for="EMS_St_Date" class="form-control" />
                <span asp-validation-for="EMS_St_Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            @await Component.InvokeAsync("Schedule", Model)
        </form>
    </div>
</div>

@*<div>
        <a asp-action="Index">Back to List</a>
    </div>*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EcomTest/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

EcomTest/Views/Shared/Components/Schedule/Default.cshtml
@model IEnumerable<EcomTest_Business.DTO.Response.ScheduleResponse>

@{
    ViewData["Title"] = "Default";
}

<h1>Default</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Cust_Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SL_NO)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EMI_Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Total_Amount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prn_Amount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Int_Amount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Balance)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EMS_St_Date)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Cust_Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SL_NO)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EMI_Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Total_Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prn_Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Int_Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Balance)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EMS_St_Date)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

EcomTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EcomTest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EcomTest</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        @RenderBody()
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - EcomTest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>